package main

// This struct is generated by jsonc

type User struct {
    Age string `json:"age"`
    Name string `json:"name"`
    Type string `json:"type"`
    UserID string `json:"user_id"`
    
}
